###### Imports

In [1]:
import requests
import json
import pandas as pd

# This file outlines the prep for the 2014 and 2019 5 year ACS estimate values to be used in a cluster analysis for finding peer communities in terms of our ageing population.

### First we will create API calls for the population and home value data from the Census Bureau ACS 5 year estimates.

###### The data we're curious about comes divided by sex or race - for now we're going to look at sex and then total them together because it's less data to deal with. You are only able to import 50 variables at once, so we're going to do total population and male population together, then female population, followed by home value. Eventually we will join them into one larger dataframe.

In [140]:
#male old and total
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'
url_str= 'https://api.census.gov/data/2014/acs/acs5?get=NAME,GEO_ID,B01001_001E,B01001_002E,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_015E,B01001_016E,B01001_017E,B01001_018E,B01001_019E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='+api_key

predicates= {}
get_vars= ["NAME","GEO_ID",'B01001_001E','B01001_020E','B01001_003E','B01001_004E','B01001_005E','B01001_006E','B01001_007E','B01001_008E','B01001_009E','B01001_010E','B01001_011E','B01001_012E','B01001_013E','B01001_014E','B01001_015E','B01001_016E','B01001_017E','B01001_018E','B01001_019E','B01001_020E','B01001_021E','B01001_022E','B01001_023E','B01001_024E','B01001_025E']
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:*"
maleold= requests.get(url_str, params= predicates)

col_names = ['CBSA','GEOID','total','mtotal','mu5','m5_9','m10_14','m15_17','m18_19','m20','m21','m22_24','m25_29','m30_34',
            'm35_39','m40_44','m45_49','m50_54','m55_59','m60_61','m62_64','m65_66','m67_69','m70_74','m75_79','m80_84','m85+','ind']
maleold=pd.DataFrame(columns=col_names, data=maleold.json()[1:])

In [141]:
#male new and total
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'
url_str= 'https://api.census.gov/data/2019/acs/acs5?get=NAME,GEO_ID,B01001_001E,B01001_002E,B01001_003E,B01001_004E,B01001_005E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_015E,B01001_016E,B01001_017E,B01001_018E,B01001_019E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='+api_key

predicates= {}
get_vars= ["NAME","GEO_ID",'B01001_001E','B01001_020E','B01001_003E','B01001_004E','B01001_005E','B01001_006E','B01001_007E','B01001_008E','B01001_009E','B01001_010E','B01001_011E','B01001_012E','B01001_013E','B01001_014E','B01001_015E','B01001_016E','B01001_017E','B01001_018E','B01001_019E','B01001_020E','B01001_021E','B01001_022E','B01001_023E','B01001_024E','B01001_025E']
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:*"
malenew= requests.get(url_str, params= predicates)

col_names = ['CBSA','GEOID','total','mtotal','mu5','m5_9','m10_14','m15_17','m18_19','m20','m21','m22_24','m25_29','m30_34',
            'm35_39','m40_44','m45_49','m50_54','m55_59','m60_61','m62_64','m65_66','m67_69','m70_74','m75_79','m80_84','m85+','ind']
malenew=pd.DataFrame(columns=col_names, data=malenew.json()[1:])

In [142]:
maleold.head(2)

,CBSA,GEOID,total,mtotal,mu5,m5_9,m10_14,m15_17,m18_19,m20,m21,m22_24,m25_29,m30_34,m35_39,m40_44,m45_49,m50_54,m55_59,m60_61,m62_64,m65_66,m67_69,m70_74,m75_79,m80_84,m85+,ind
0,"Homosassa Springs, FL Metro Area",310M200US26140,139771,67497,2639,2404,3599,2170,1310,544,713,1735,2686,2332,3038,2785,4035,4587,4835,2170,3453,2319,4543,5434,4898,3099,2169,26140
1,"Hickory-Lenoir-Morganton, NC Metro Area",310M200US25860,363936,180006,10129,11631,11662,7909,5182,2955,2286,6349,9750,10134,11868,12959,13986,13513,12607,4571,6761,4305,5277,6744,4547,2959,1922,25860

In [143]:
malenew.head(2)

,CBSA,GEOID,total,mtotal,mu5,m5_9,m10_14,m15_17,m18_19,m20,m21,m22_24,m25_29,m30_34,m35_39,m40_44,m45_49,m50_54,m55_59,m60_61,m62_64,m65_66,m67_69,m70_74,m75_79,m80_84,m85+,ind
0,"Big Stone Gap, VA Micro Area",310M500US13720,42456,22025,1160,1149,1253,776,583,356,238,1035,1791,1490,1432,1480,1430,1388,1465,768,853,425,861,858,559,340,335,13720
1,"Billings, MT Metro Area",310M500US13740,179071,88433,5510,6170,5862,3575,1936,774,904,3687,5856,5880,5701,5403,5355,5446,6014,2780,3459,2176,3299,3299,2395,1420,1532,13740

In [144]:
#female old
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'
url_str= 'https://api.census.gov/data/2014/acs/acs5?get=NAME,GEO_ID,B01001_026E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_039E,B01001_040E,B01001_041E,B01001_042E,B01001_043E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='+api_key

predicates= {}
get_vars= ["NAME","GEO_ID",'B01001_026E','B01001_027E','B01001_028E','B01001_029E','B01001_030E','B01001_031E','B01001_032E','B01001_033E','B01001_034E','B01001_035E','B01001_036E','B01001_037E','B01001_038E','B01001_039E','B01001_040E','B01001_041E','B01001_042E','B01001_043E','B01001_044E','B01001_045E','B01001_046E','B01001_047E','B01001_048E','B01001_049E']
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:*"
femaleold= requests.get(url_str, params= predicates)

col_names = ['CBSA','GEOID','ftotal', 'fu5','f5_9','f10_14','f15_17','f18_19','f20','f21','f22_24','f25_29','f30_34',
            'f35_39','f40_44','f45_49','f50_54','f55_59','f60_61','f62_64','f65_66','f67_69','f70_74','f75_79','f80_84','f85+','ind']
femaleold=pd.DataFrame(columns=col_names, data=femaleold.json()[1:])

In [145]:
#female new
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'
url_str= 'https://api.census.gov/data/2019/acs/acs5?get=NAME,GEO_ID,B01001_026E,B01001_027E,B01001_028E,B01001_029E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_039E,B01001_040E,B01001_041E,B01001_042E,B01001_043E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='+api_key

predicates= {}
get_vars= ["NAME","GEO_ID",'B01001_026E','B01001_027E','B01001_028E','B01001_029E','B01001_030E','B01001_031E','B01001_032E','B01001_033E','B01001_034E','B01001_035E','B01001_036E','B01001_037E','B01001_038E','B01001_039E','B01001_040E','B01001_041E','B01001_042E','B01001_043E','B01001_044E','B01001_045E','B01001_046E','B01001_047E','B01001_048E','B01001_049E']
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:*"
femalenew= requests.get(url_str, params= predicates)

col_names = ['CBSA','GEOID','ftotal', 'fu5','f5_9','f10_14','f15_17','f18_19','f20','f21','f22_24','f25_29','f30_34',
            'f35_39','f40_44','f45_49','f50_54','f55_59','f60_61','f62_64','f65_66','f67_69','f70_74','f75_79','f80_84','f85+','ind']
femalenew=pd.DataFrame(columns=col_names, data=femalenew.json()[1:])

In [146]:
femaleold.head(2)

,CBSA,GEOID,ftotal,fu5,f5_9,f10_14,f15_17,f18_19,f20,f21,f22_24,f25_29,f30_34,f35_39,f40_44,f45_49,f50_54,f55_59,f60_61,f62_64,f65_66,f67_69,f70_74,f75_79,f80_84,f85+,ind
0,"Homosassa Springs, FL Metro Area",310M200US26140,72274,2793,2634,3197,2052,1241,587,719,1283,2513,2446,2769,3531,4279,5174,5917,2541,4107,2612,4327,6294,4520,3354,3384,26140
1,"Hickory-Lenoir-Morganton, NC Metro Area",310M200US25860,183930,9973,10596,12065,6895,4132,2428,2220,5832,9471,10089,11181,13228,13332,13845,12833,5074,7537,4340,6002,7976,6162,4219,4500,25860

In [147]:
femalenew.head(2)

,CBSA,GEOID,ftotal,fu5,f5_9,f10_14,f15_17,f18_19,f20,f21,f22_24,f25_29,f30_34,f35_39,f40_44,f45_49,f50_54,f55_59,f60_61,f62_64,f65_66,f67_69,f70_74,f75_79,f80_84,f85+,ind
0,"Big Stone Gap, VA Micro Area",310M500US13720,20431,1054,1297,1012,702,447,345,172,606,1360,1143,1272,1123,1317,1248,1611,596,1047,740,646,947,638,573,535,13720
1,"Billings, MT Metro Area",310M500US13740,90638,5301,5588,6219,3210,1857,743,944,3251,5905,6083,5596,5425,5204,5681,6679,2569,3502,2014,3357,4053,2710,2050,2697,13740

In [148]:
#home value old
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'
url_str= 'https://api.census.gov/data/2014/acs/acs5?get=NAME,GEO_ID,B25077_001E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='+api_key

predicates= {}
get_vars= ["NAME","GEO_ID",'B25077_001E']
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:*"
homeold= requests.get(url_str, params= predicates)

col_names = ['CBSA','GEOID','homevalue','ind']
homeold=pd.DataFrame(columns=col_names, data=homeold.json()[1:])

In [149]:
#home value new
api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'
url_str= 'https://api.census.gov/data/2019/acs/acs5?get=NAME,GEO_ID,B25077_001E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='+api_key

predicates= {}
get_vars= ["NAME","GEO_ID",'B25077_001E']
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:*"
homenew= requests.get(url_str, params= predicates)

col_names = ['CBSA','GEOID','homevalue','ind']
homenew=pd.DataFrame(columns=col_names, data=homenew.json()[1:])

In [150]:
homeold.head(2)

                                      CBSA           GEOID homevalue    ind
0         Homosassa Springs, FL Metro Area  310M200US26140    113500  26140
1  Hickory-Lenoir-Morganton, NC Metro Area  310M200US25860    120200  25860

In [151]:
homenew.head(2)

                           CBSA           GEOID homevalue    ind
0  Big Stone Gap, VA Micro Area  310M500US13720     86200  13720
1       Billings, MT Metro Area  310M500US13740    227900  13740

Join all of the "old" back together into one bigger df:

In [152]:
old = pd.merge(maleold, femaleold, how = 'inner', on = 'GEOID')

In [153]:
old = pd.merge(old, homeold, how = 'inner', on = 'GEOID')

Do the same for "new":

In [154]:
new = pd.merge(malenew, femalenew, how = 'inner', on = 'GEOID')

In [155]:
new = pd.merge(new, homenew, how = 'inner', on = 'GEOID')

Create something distinctive for the "old" data columns and then merge the two:

In [156]:
#for loop for renaming them with an O* for old at the beginning of each column
for col in old.columns:
    old.rename(columns = {col:'O*'+col}, inplace = True)

In [157]:
old.head()

,O*CBSA_x,O*GEOID,O*total,O*mtotal,O*mu5,O*m5_9,O*m10_14,O*m15_17,O*m18_19,O*m20,O*m21,O*m22_24,O*m25_29,O*m30_34,O*m35_39,O*m40_44,O*m45_49,O*m50_54,O*m55_59,O*m60_61,O*m62_64,O*m65_66,O*m67_69,O*m70_74,O*m75_79,O*m80_84,O*m85+,O*ind_x,O*CBSA_y,O*ftotal,O*fu5,O*f5_9,O*f10_14,O*f15_17,O*f18_19,O*f20,O*f21,O*f22_24,O*f25_29,O*f30_34,O*f35_39,O*f40_44,O*f45_49,O*f50_54,O*f55_59,O*f60_61,O*f62_64,O*f65_66,O*f67_69,O*f70_74,O*f75_79,O*f80_84,O*f85+,O*ind_y,O*CBSA,O*homevalue,O*ind
0,"Homosassa Springs, FL Metro Area",310M200US26140,139771,67497,2639,2404,3599,2170,1310,544,713,1735,2686,2332,3038,2785,4035,4587,4835,2170,3453,2319,4543,5434,4898,3099,2169,26140,"Homosassa Springs, FL Metro Area",72274,2793,2634,3197,2052,1241,587,719,1283,2513,2446,2769,3531,4279,5174,5917,2541,4107,2612,4327,6294,4520,3354,3384,26140,"Homosassa Springs, FL Metro Area",113500,26140
1,"Hickory-Lenoir-Morganton, NC Metro Area",310M200US25860,363936,180006,10129,11631,11662,7909,5182,2955,2286,6349,9750,10134,11868,12959,13986,13513,12607,4571,6761,4305,5277,6744,4547,2959,1922,25860,"Hickory-Lenoir-Morganton, NC Metro Area",183930,9973,10596,12065,6895,4132,2428,2220,5832,9471,10089,11181,13228,13332,13845,12833,5074,7537,4340,6002,7976,6162,4219,4500,25860,"Hickory-Lenoir-Morganton, NC Metro Area",120200,25860
2,"Hobbs, NM Micro Area",310M200US26020,66876,34219,2909,2708,2964,1522,1137,500,440,1518,2612,2675,2122,2092,2090,2206,1854,696,868,456,626,806,675,448,295,26020,"Hobbs, NM Micro Area",32657,2881,2747,2692,1509,892,648,378,1275,2283,2113,2205,1710,1907,2109,2067,583,803,527,625,898,833,580,392,26020,"Hobbs, NM Micro Area",101400,26020
3,"Holland, MI Micro Area",310M200US26090,112266,55910,3599,4145,4271,2617,1315,736,512,1850,3009,3209,3366,3708,4225,4500,4298,1415,1887,1044,1437,1980,1224,935,628,26090,"Holland, MI Micro Area",56356,3468,3958,3982,2504,1289,654,701,1655,2959,3284,3277,3729,4136,4547,3942,1721,1965,1112,1695,1934,1579,946,1319,26090,"Holland, MI Micro Area",137500,26090
4,"Hood River, OR Micro Area",310M200US26220,22620,11169,800,819,850,381,229,89,146,483,694,732,535,958,818,856,747,305,368,197,191,459,233,157,122,26220,"Hood River, OR Micro Area",11451,716,742,860,574,154,45,140,511,631,681,824,768,800,866,819,263,326,214,234,419,322,226,316,26220,"Hood River, OR Micro Area",309500,26220

In [158]:
#rename the O*GEOID to the reverted column name to join on it
old = old.rename(columns = {'O*GEOID':'GEOID', 'O*CBSA':'CBSA'})

In [159]:
#make sure the datatypes are correct
new['GEOID'] = new['GEOID'].astype(str)
old['GEOID'] = old['GEOID'].astype(str)
new['CBSA'] = new['CBSA'].astype(str)
old['CBSA'] = old['CBSA'].astype(str)

In [160]:
data = pd.merge(new, old, on='CBSA', how = 'inner')

Check out our datatypes and any extra columns from the join that are no longer necessary.

In [161]:
#set parameter to show all columns
pd.set_option('max_columns', None)

In [162]:
data.head()

,CBSA_x,GEOID_x,total,mtotal,mu5,m5_9,m10_14,m15_17,m18_19,m20,m21,m22_24,m25_29,m30_34,m35_39,m40_44,m45_49,m50_54,m55_59,m60_61,m62_64,m65_66,m67_69,m70_74,m75_79,m80_84,m85+,ind_x,CBSA_y,ftotal,fu5,f5_9,f10_14,f15_17,f18_19,f20,f21,f22_24,f25_29,f30_34,f35_39,f40_44,f45_49,f50_54,f55_59,f60_61,f62_64,f65_66,f67_69,f70_74,f75_79,f80_84,f85+,ind_y,CBSA,homevalue,ind,O*CBSA_x,GEOID_y,O*total,O*mtotal,O*mu5,O*m5_9,O*m10_14,O*m15_17,O*m18_19,O*m20,O*m21,O*m22_24,O*m25_29,O*m30_34,O*m35_39,O*m40_44,O*m45_49,O*m50_54,O*m55_59,O*m60_61,O*m62_64,O*m65_66,O*m67_69,O*m70_74,O*m75_79,O*m80_84,O*m85+,O*ind_x,O*CBSA_y,O*ftotal,O*fu5,O*f5_9,O*f10_14,O*f15_17,O*f18_19,O*f20,O*f21,O*f22_24,O*f25_29,O*f30_34,O*f35_39,O*f40_44,O*f45_49,O*f50_54,O*f55_59,O*f60_61,O*f62_64,O*f65_66,O*f67_69,O*f70_74,O*f75_79,O*f80_84,O*f85+,O*ind_y,O*homevalue,O*ind
0,"Big Stone Gap, VA Micro Area",310M500US13720,42456,22025,1160,1149,1253,776,583,356,238,1035,1791,1490,1432,1480,1430,1388,1465,768,853,425,861,858,559,340,335,13720,"Big Stone Gap, VA Micro Area",20431,1054,1297,1012,702,447,345,172,606,1360,1143,1272,1123,1317,1248,1611,596,1047,740,646,947,638,573,535,13720,"Big Stone Gap, VA Micro Area",86200,13720,"Big Stone Gap, VA Micro Area",310M200US13720,60499,30657,1614,1942,1599,1070,826,443,333,1527,2149,2257,1918,2250,2176,2222,1710,959,1513,668,951,1034,755,430,311,13720,"Big Stone Gap, VA Micro Area",29842,1605,1674,1795,1076,801,521,484,1008,1650,1667,1911,1888,2065,2158,1961,834,1569,605,860,1347,1013,646,704,13720,82800,13720
1,"Billings, MT Metro Area",310M500US13740,179071,88433,5510,6170,5862,3575,1936,774,904,3687,5856,5880,5701,5403,5355,5446,6014,2780,3459,2176,3299,3299,2395,1420,1532,13740,"Billings, MT Metro Area",90638,5301,5588,6219,3210,1857,743,944,3251,5905,6083,5596,5425,5204,5681,6679,2569,3502,2014,3357,4053,2710,2050,2697,13740,"Billings, MT Metro Area",227900,13740,"Billings, MT Metro Area",310M200US13740,162892,79941,5415,5422,5184,3152,2033,993,1071,2735,5529,5384,4883,4960,5268,5976,5848,2202,2950,1611,2004,2704,1942,1586,1089,13740,"Billings, MT Metro Area",82951,5205,5494,5052,3050,1722,1018,922,3161,5581,5401,4971,4769,5403,6224,5813,2420,3039,1952,2190,2776,2276,1989,2523,13740,187100,13740
2,"Binghamton, NY Metro Area",310M500US13780,241874,119221,6476,7128,6619,4518,4705,2593,2894,5923,7021,6628,6571,5879,6906,7872,9256,3942,4230,2808,3735,5025,4163,2167,2162,13780,"Binghamton, NY Metro Area",122653,6104,6196,6595,4263,4564,2517,2145,5874,6639,6328,6482,6330,6850,8269,9712,3461,4673,3223,3893,5733,4678,3388,4736,13780,"Binghamton, NY Metro Area",117600,13780,"Binghamton, NY Metro Area",310M200US13780,249261,122423,6602,7244,7375,4749,5299,2628,3001,5257,7325,6938,6854,6644,8153,9796,8886,3167,4452,2357,3266,4393,3640,2605,1792,13780,"Binghamton, NY Metro Area",126838,6273,6931,6989,4635,4683,2297,2124,5849,7032,6580,6308,7209,8776,10084,8672,3107,5202,2629,3967,4790,4246,3734,4721,13780,108800,13780
3,"Birmingham-Hoover, AL Metro Area",310M500US13820,1085330,521496,34020,35330,36232,22069,12928,6687,6550,19721,37169,35364,34445,33803,34093,33920,34366,13750,18921,11914,15273,18629,11772,8176,6364,13820,"Birmingham-Hoover, AL Metro Area",563834,33618,34098,34317,20814,12937,7540,5998,19872,38767,37822,36442,36075,36622,36524,38226,15788,21722,13729,17591,23233,16738,12956,12405,13820,"Birmingham-Hoover, AL Metro Area",165200,13820,"Birmingham-Hoover, AL Metro Area",310M200US13820,1135534,546799,37407,37502,38646,23132,14436,7607,7440,20762,37301,37933,34997,38338,37785,39511,36556,13426,18552,10763,12759,16487,11792,7820,5847,13820,"Birmingham-Hoover, AL Metro Area",588735,35890,35840,37332,21865,13503,6454,7941,22869,40099,39780,36947,39815,40045,42833,40701,15300,21088,12123,15742,20136,16587,13124,12721,13820,144000,13820
4,"Bismarck, ND Metro Area",310M500US13900,127503,64036,4382,4386,4002,2228,1558,731,865,2573,4842,5133,4758,3710,3722,4016,4350,1672,2137,1356,1865,2200,1477,940,1133,13900,"Bismarck, ND Metro Area",63467,4146,4092,3839,2096,1629,739,590,2506,4666,4401,4121,3565,3352,3809,4722,1729,2262,1505,1958,2316,1673,1550,2201,13900,"Bismarck, ND Metro Area",249000,13900,"Bismarck, ND Metro Area",310M200US13900,120688,60007,4042,4132,3827,2411,1561,716,990,2502,4822,4413,3890,3408,3956,4334,4079,1527,2029,1021,1336,1826,1151,1116,918,13900,"Bismarck, ND Metro Area",60681,4015,4106,3235,2198,1669,912,1015,2455,4189,4123,3480,3430,3952,4531,4335,1502,2009,1115,1252,2172,1709,1353,1924,13900,171000,13900

Drop the indices and extra CBSA name column, rename the one you're going to keep, then convert all numeric columns to int64 as we're going to be performing mathematical operations on them.

In [163]:
#drop the indices and extra state name
data = data.drop(columns=['ind','ind_x','CBSA_y','ind_y','CBSA','ind','O*CBSA_x','GEOID_y','O*ind_x','O*CBSA_y','O*ind_y','O*ind','GEOID_y'])

In [164]:
data = data.rename(columns={'CBSA_x':'CBSA','GEOID_x':'GEOID'})

In [165]:
#convert all numeric columns to integers
cols = ['total','mtotal','mu5','m5_9','m10_14','m15_17','m18_19','m20','m21','m22_24','m25_29','m30_34',
        'm35_39','m40_44','m45_49','m50_54','m55_59','m60_61','m62_64','m65_66','m67_69','m70_74','m75_79',
        'm80_84','m85+','ftotal', 'fu5','f5_9','f10_14','f15_17','f18_19','f20','f21','f22_24','f25_29',
        'f30_34','f35_39','f40_44','f45_49','f50_54','f55_59','f60_61','f62_64','f65_66','f67_69','f70_74',
        'f75_79','f80_84','f85+','homevalue','O*total','O*mtotal','O*mu5','O*m5_9','O*m10_14','O*m15_17','O*m18_19','O*m20',
        'O*m21','O*m22_24','O*m25_29','O*m30_34','O*m35_39','O*m40_44','O*m45_49','O*m50_54','O*m55_59','O*m60_61','O*m62_64','O*m65_66',
        'O*m67_69','O*m70_74','O*m75_79','O*m80_84','O*m85+','O*ftotal', 'O*fu5','O*f5_9','O*f10_14','O*f15_17','O*f18_19','O*f20','O*f21',
        'O*f22_24','O*f25_29','O*f30_34','O*f35_39','O*f40_44','O*f45_49','O*f50_54','O*f55_59','O*f60_61','O*f62_64','O*f65_66','O*f67_69',
        'O*f70_74','O*f75_79','O*f80_84','O*f85+','O*homevalue']

data[cols]=data[cols].apply(pd.to_numeric, errors='coerce', axis=1)

Check that the last few steps were effective.

In [166]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 859 entries, 0 to 858
Data columns (total 102 columns):
 #    Column       Dtype
---   ------       -----
 0    CBSA         object
 1    GEOID        object
 2    total        int64
 3    mtotal       int64
 4    mu5          int64
 5    m5_9         int64
 6    m10_14       int64
 7    m15_17       int64
 8    m18_19       int64
 9    m20          int64
 10   m21          int64
 11   m22_24       int64
 12   m25_29       int64
 13   m30_34       int64
 14   m35_39       int64
 15   m40_44       int64
 16   m45_49       int64
 17   m50_54       int64
 18   m55_59       int64
 19   m60_61       int64
 20   m62_64       int64
 21   m65_66       int64
 22   m67_69       int64
 23   m70_74       int64
 24   m75_79       int64
 25   m80_84       int64
 26   m85+         int64
 27   ftotal       int64
 28   fu5          int64
 29   f5_9         int64
 30   f10_14       int64
 31   f15_17       int64
 32   f18_19       int64
 33   f20          int64
 34   f21          int64
 35   f22_24       int64
 36   f25_29       int64
 37   f30_34       int64
 38   f35_39       int64
 39   f40_44       int64
 40   f45_49       int64
 41   f50_54       int64
 42   f55_59       int64
 43   f60_61       int64
 44   f62_64       int64
 45   f65_66       int64
 46   f67_69       int64
 47   f70_74       int64
 48   f75_79       int64
 49   f80_84       int64
 50   f85+         int64
 51   homevalue    int64
 52   O*total      int64
 53   O*mtotal     int64
 54   O*mu5        int64
 55   O*m5_9       int64
 56   O*m10_14     int64
 57   O*m15_17     int64
 58   O*m18_19     int64
 59   O*m20        int64
 60   O*m21        int64
 61   O*m22_24     int64
 62   O*m25_29     int64
 63   O*m30_34     int64
 64   O*m35_39     int64
 65   O*m40_44     int64
 66   O*m45_49     int64
 67   O*m50_54     int64
 68   O*m55_59     int64
 69   O*m60_61     int64
 70   O*m62_64     int64
 71   O*m65_66     int64
 72   O*m67_69     int64
 73   O*m70_74     int64
 74   O*m75_79     int64
 75   O*m80_84     int64
 76   O*m85+       int64
 77   O*ftotal     int64
 78   O*fu5        int64
 79   O*f5_9       int64
 80   O*f10_14     int64
 81   O*f15_17     int64
 82   O*f18_19     int64
 83   O*f20        int64
 84   O*f21        int64
 85   O*f22_24     int64
 86   O*f25_29     int64
 87   O*f30_34     int64
 88   O*f35_39     int64
 89   O*f40_44     int64
 90   O*f45_49     int64
 91   O*f50_54     int64
 92   O*f55_59     int64
 93   O*f60_61     int64
 94   O*f62_64     int64
 95   O*f65_66     int64
 96   O*f67_69     int64
 97   O*f70_74     int64
 98   O*f75_79     int64
 99   O*f80_84     int64
 100  O*f85+       int64
 101  O*homevalue  int64
dtypes: int64(100), object(2)
memory usage: 691.2+ KB

Create columns of totals for each one of these age groups.

In [167]:
#create totals columns for "new":
data['tu5'] = data['mu5']+data['fu5']
data['t5_9'] = data['m5_9']+data['f5_9']
data['t10_14'] = data['m10_14']+data['f10_14']
data['t15_17'] = data['m15_17']+data['f15_17']
data['t18_19'] = data['m18_19']+data['f18_19']
data['t20'] = data['m20']+data['f20']
data['t21'] = data['m21']+data['f21']
data['t22_24'] = data['m22_24']+data['f22_24']
data['t25_29'] = data['m25_29']+data['f25_29']
data['t30_34'] = data['m30_34']+data['f30_34']
data['t35_39'] = data['m35_39']+data['f35_39']
data['t40_44'] = data['m40_44']+data['f40_44']
data['t45_49'] = data['m45_49']+data['f45_49']
data['t50_54'] = data['m50_54']+data['f50_54']
data['t55_59'] = data['m55_59']+data['f55_59']
data['t60_61'] = data['m60_61']+data['f60_61']
data['t62_64'] = data['m62_64']+data['f62_64']
data['t65_66'] = data['m65_66']+data['f65_66']
data['t67_69'] = data['m67_69']+data['f67_69']
data['t70_74'] = data['m70_74']+data['f70_74']
data['t75_79'] = data['m75_79']+data['f75_79']
data['t80_84'] = data['m80_84']+data['f80_84']
data['t85+'] = data['m85+']+data['f85+']

data = data.copy()

C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['tu5'] = data['mu5']+data['fu5']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t5_9'] = data['m5_9']+data['f5_9']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t10_14'] = data['m10_14']+data['f10_14']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t15_17'] = data['m15_17']+data['f15_17']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t18_19'] = data['m18_19']+data['f18_19']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t20'] = data['m20']+data['f20']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t21'] = data['m21']+data['f21']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t22_24'] = data['m22_24']+data['f22_24']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t25_29'] = data['m25_29']+data['f25_29']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t30_34'] = data['m30_34']+data['f30_34']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t35_39'] = data['m35_39']+data['f35_39']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t40_44'] = data['m40_44']+data['f40_44']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t45_49'] = data['m45_49']+data['f45_49']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t50_54'] = data['m50_54']+data['f50_54']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t55_59'] = data['m55_59']+data['f55_59']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t60_61'] = data['m60_61']+data['f60_61']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t62_64'] = data['m62_64']+data['f62_64']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t65_66'] = data['m65_66']+data['f65_66']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t67_69'] = data['m67_69']+data['f67_69']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t70_74'] = data['m70_74']+data['f70_74']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t75_79'] = data['m75_79']+data['f75_79']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t80_84'] = data['m80_84']+data['f80_84']
C:\Users\jmccall\AppData\Local\Temp/ipykernel_8028/2016445353.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  data['t85+'] = data['m85+']+data['f85+']

In [191]:
#do the same for "old":
data['O*tu5'] = data['O*mu5']+data['O*fu5']
data['O*t5_9'] = data['O*m5_9']+data['O*f5_9']
data['O*t10_14'] = data['O*m10_14']+data['O*f10_14']
data['O*t15_17'] = data['O*m15_17']+data['O*f15_17']
data['O*t18_19'] = data['O*m18_19']+data['O*f18_19']
data['O*t20'] = data['O*m20']+data['O*f20']
data['O*t21'] = data['O*m21']+data['O*f21']
data['O*t22_24'] = data['O*m22_24']+data['O*f22_24']
data['O*t25_29'] = data['O*m25_29']+data['O*f25_29']
data['O*t30_34'] = data['O*m30_34']+data['O*f30_34']
data['O*t35_39'] = data['O*m35_39']+data['O*f35_39']
data['O*t40_44'] = data['O*m40_44']+data['O*f40_44']
data['O*t45_49'] = data['O*m45_49']+data['O*f45_49']
data['O*t50_54'] = data['O*m50_54']+data['O*f50_54']
data['O*t55_59'] = data['O*m55_59']+data['O*f55_59']
data['O*t60_61'] = data['O*m60_61']+data['O*f60_61']
data['O*t62_64'] = data['O*m62_64']+data['O*f62_64']
data['O*t65_66'] = data['O*m65_66']+data['O*f65_66']
data['O*t67_69'] = data['O*m67_69']+data['O*f67_69']
data['O*t70_74'] = data['O*m70_74']+data['O*f70_74']
data['O*t75_79'] = data['O*m75_79']+data['O*f75_79']
data['O*t80_84'] = data['O*m80_84']+data['O*f80_84']
data['O*t85+'] = data['O*m85+']+data['O*f85+']

data = data.copy()

KeyError: 'O*mu5'

## Create groups for analysis. Since we're looking at ageing services, it makes sense to group people into some rough "stage of life" that is predicated on services provided to them or their position in the workforce.

###### So we're going to do:  
- under 18  
- 18 - 64  
- 65+  

Note that we're also eliminating the gender divide, we can always come back and disaggregate this but it doesn't seem particularly relevant now.

In [170]:
#child
data['child'] = data['tu5']+data['t5_9']+data['t10_14']+data['t15_17']
data['O*child'] = data['O*tu5']+data['O*t5_9']+data['O*t10_14']+data['O*t15_17']
#taxbase
data['taxbase'] = data['t18_19']+data['t20']+data['t21']+data['t22_24']+data['t25_29']+data['t30_34']+data['t35_39']+data['t40_44']+data['t45_49']+data['t50_54']+data['t55_59']+data['t60_61']+data['t62_64']
data['O*taxbase'] = data['O*t18_19']+data['O*t20']+data['O*t21']+data['O*t22_24']+data['O*t25_29']+data['O*t30_34']+data['O*t35_39']+data['O*t40_44']+data['O*t45_49']+data['O*t50_54']+data['O*t55_59']+data['O*t60_61']+data['O*t62_64']
#over 65
data['O65'] = data['t65_66']+data['t67_69']+data['t70_74']+data['t75_79']+data['t80_84']+data['t85+']
data['O*O65'] = data['O*t65_66']+data['O*t67_69']+data['O*t70_74']+data['O*t75_79']+data['O*t80_84']+data['O*t85+']

data = data.copy()

Make these groups into shares of the total.

In [172]:
data['Pchild']=round(data['child']*100/data['total'],1)
data['Ptaxbase']=round(data['taxbase']*100/data['total'],1)
data['PO65']=round(data['O65']*100/data['total'],1)
data['O*Pchild']=round(data['O*child']*100/data['O*total'],1)
data['O*Ptaxbase']=round(data['O*taxbase']*100/data['O*total'],1)
data['O*PO65']=round(data['O*O65']*100/data['O*total'],1)

data = data.copy()

In [173]:
data.head(2)

,CBSA,GEOID,total,mtotal,mu5,m5_9,m10_14,m15_17,m18_19,m20,m21,m22_24,m25_29,m30_34,m35_39,m40_44,m45_49,m50_54,m55_59,m60_61,m62_64,m65_66,m67_69,m70_74,m75_79,m80_84,m85+,ftotal,fu5,f5_9,f10_14,f15_17,f18_19,f20,f21,f22_24,f25_29,f30_34,f35_39,f40_44,f45_49,f50_54,f55_59,f60_61,f62_64,f65_66,f67_69,f70_74,f75_79,f80_84,f85+,homevalue,O*total,O*mtotal,O*mu5,O*m5_9,O*m10_14,O*m15_17,O*m18_19,O*m20,O*m21,O*m22_24,O*m25_29,O*m30_34,O*m35_39,O*m40_44,O*m45_49,O*m50_54,O*m55_59,O*m60_61,O*m62_64,O*m65_66,O*m67_69,O*m70_74,O*m75_79,O*m80_84,O*m85+,O*ftotal,O*fu5,O*f5_9,O*f10_14,O*f15_17,O*f18_19,O*f20,O*f21,O*f22_24,O*f25_29,O*f30_34,O*f35_39,O*f40_44,O*f45_49,O*f50_54,O*f55_59,O*f60_61,O*f62_64,O*f65_66,O*f67_69,O*f70_74,O*f75_79,O*f80_84,O*f85+,O*homevalue,tu5,t5_9,t10_14,t15_17,t18_19,t20,t21,t22_24,t25_29,t30_34,t35_39,t40_44,t45_49,t50_54,t55_59,t60_61,t62_64,t65_66,t67_69,t70_74,t75_79,t80_84,t85+,O*tu5,O*t5_9,O*t10_14,O*t15_17,O*t18_19,O*t20,O*t21,O*t22_24,O*t25_29,O*t30_34,O*t35_39,O*t40_44,O*t45_49,O*t50_54,O*t55_59,O*t60_61,O*t62_64,O*t65_66,O*t67_69,O*t70_74,O*t75_79,O*t80_84,O*t85+,child,O*child,taxbase,O*taxbase,O65,O*O65,Pchild,Ptaxbase,PO65,O*Pchild,O*Ptaxbase,O*PO65
0,"Big Stone Gap, VA Micro Area",310M500US13720,42456,22025,1160,1149,1253,776,583,356,238,1035,1791,1490,1432,1480,1430,1388,1465,768,853,425,861,858,559,340,335,20431,1054,1297,1012,702,447,345,172,606,1360,1143,1272,1123,1317,1248,1611,596,1047,740,646,947,638,573,535,86200,60499,30657,1614,1942,1599,1070,826,443,333,1527,2149,2257,1918,2250,2176,2222,1710,959,1513,668,951,1034,755,430,311,29842,1605,1674,1795,1076,801,521,484,1008,1650,1667,1911,1888,2065,2158,1961,834,1569,605,860,1347,1013,646,704,82800,2214,2446,2265,1478,1030,701,410,1641,3151,2633,2704,2603,2747,2636,3076,1364,1900,1165,1507,1805,1197,913,870,3219,3616,3394,2146,1627,964,817,2535,3799,3924,3829,4138,4241,4380,3671,1793,3082,1273,1811,2381,1768,1076,1015,8403,12375,26596,38800,7457,9324,19.8,62.6,17.6,20.5,64.1,15.4
1,"Billings, MT Metro Area",310M500US13740,179071,88433,5510,6170,5862,3575,1936,774,904,3687,5856,5880,5701,5403,5355,5446,6014,2780,3459,2176,3299,3299,2395,1420,1532,90638,5301,5588,6219,3210,1857,743,944,3251,5905,6083,5596,5425,5204,5681,6679,2569,3502,2014,3357,4053,2710,2050,2697,227900,162892,79941,5415,5422,5184,3152,2033,993,1071,2735,5529,5384,4883,4960,5268,5976,5848,2202,2950,1611,2004,2704,1942,1586,1089,82951,5205,5494,5052,3050,1722,1018,922,3161,5581,5401,4971,4769,5403,6224,5813,2420,3039,1952,2190,2776,2276,1989,2523,187100,10811,11758,12081,6785,3793,1517,1848,6938,11761,11963,11297,10828,10559,11127,12693,5349,6961,4190,6656,7352,5105,3470,4229,10620,10916,10236,6202,3755,2011,1993,5896,11110,10785,9854,9729,10671,12200,11661,4622,5989,3563,4194,5480,4218,3575,3612,41435,37974,106634,100276,31002,24642,23.1,59.5,17.3,23.3,61.6,15.1

Make a separate dataframe of only these created groups and their shares

In [174]:
data = data[['CBSA', 'GEOID', 'total', 'child', 'taxbase', 'O65', 
           'Pchild', 'Ptaxbase', 'PO65', 'homevalue', 'O*total','O*child', 'O*taxbase', 'O*O65', 
           'O*Pchild', 'O*Ptaxbase', 'O*PO65', 'O*homevalue']]

In [175]:
data.head()

,CBSA,GEOID,total,child,taxbase,O65,Pchild,Ptaxbase,PO65,homevalue,O*total,O*child,O*taxbase,O*O65,O*Pchild,O*Ptaxbase,O*PO65,O*homevalue
0,"Big Stone Gap, VA Micro Area",310M500US13720,42456,8403,26596,7457,19.8,62.6,17.6,86200,60499,12375,38800,9324,20.5,64.1,15.4,82800
1,"Billings, MT Metro Area",310M500US13740,179071,41435,106634,31002,23.1,59.5,17.3,227900,162892,37974,100276,24642,23.3,61.6,15.1,187100
2,"Binghamton, NY Metro Area",310M500US13780,241874,47899,148264,45711,19.8,61.3,18.9,117600,249261,50798,156323,42140,20.4,62.7,16.9,108800
3,"Birmingham-Hoover, AL Metro Area",310M500US13820,1085330,250498,666052,168780,23.1,61.4,15.6,165200,1135534,267614,712019,155901,23.6,62.7,13.7,144000
4,"Bismarck, ND Metro Area",310M500US13900,127503,29171,78158,20174,22.9,61.3,15.8,249000,120688,27966,75829,16893,23.2,62.8,14.0,171000

Let's split the full GEOID so that we have the CBSA FIPS, let's also split up the CBSA names so that we have the name, state, and Metro or Micro Area designation. Start with the geography name.

In [176]:
# Split the CBSA column at the comma then name the new column as the first column you index into
name = data['CBSA'].str.split(pat = ',', expand = True)
name

                             0               1
0                Big Stone Gap   VA Micro Area
1                     Billings   MT Metro Area
2                   Binghamton   NY Metro Area
3            Birmingham-Hoover   AL Metro Area
4                     Bismarck   ND Metro Area
..                         ...             ...
854                  Opelousas   LA Micro Area
855                 Orangeburg   SC Micro Area
856  Orlando-Kissimmee-Sanford   FL Metro Area
857                 Fort Dodge   IA Micro Area
858               Fort Collins   CO Metro Area

[859 rows x 2 columns]

In [177]:
data['Name'] = name[0]
state_area = name[1]
state_area

0       VA Micro Area
1       MT Metro Area
2       NY Metro Area
3       AL Metro Area
4       ND Metro Area
            ...
854     LA Micro Area
855     SC Micro Area
856     FL Metro Area
857     IA Micro Area
858     CO Metro Area
Name: 1, Length: 859, dtype: object

In [178]:
# Next we can split this again after the first two figures which indicate the State
state = state_area.str.slice(stop = 3)
state

0       VA
1       MT
2       NY
3       AL
4       ND
      ...
854     LA
855     SC
856     FL
857     IA
858     CO
Name: 1, Length: 859, dtype: object

In [179]:
data['State'] = state

In [180]:
area = state_area.str.slice(start = 3, stop = 9)
area

0       Micro
1       Metro
2       Metro
3       Metro
4       Metro
        ...
854     Micro
855     Micro
856     Metro
857     Micro
858     Metro
Name: 1, Length: 859, dtype: object

In [181]:
data['Area'] = area

Now we're going to split the GEOIDs.

In [182]:
data['CBSAFIPS'] = data['GEOID'].str.slice(start = 9)

In [183]:
data.head()

,CBSA,GEOID,total,child,taxbase,O65,Pchild,Ptaxbase,PO65,homevalue,O*total,O*child,O*taxbase,O*O65,O*Pchild,O*Ptaxbase,O*PO65,O*homevalue,Name,State,Area,CBSAFIPS
0,"Big Stone Gap, VA Micro Area",310M500US13720,42456,8403,26596,7457,19.8,62.6,17.6,86200,60499,12375,38800,9324,20.5,64.1,15.4,82800,Big Stone Gap,VA,Micro,13720
1,"Billings, MT Metro Area",310M500US13740,179071,41435,106634,31002,23.1,59.5,17.3,227900,162892,37974,100276,24642,23.3,61.6,15.1,187100,Billings,MT,Metro,13740
2,"Binghamton, NY Metro Area",310M500US13780,241874,47899,148264,45711,19.8,61.3,18.9,117600,249261,50798,156323,42140,20.4,62.7,16.9,108800,Binghamton,NY,Metro,13780
3,"Birmingham-Hoover, AL Metro Area",310M500US13820,1085330,250498,666052,168780,23.1,61.4,15.6,165200,1135534,267614,712019,155901,23.6,62.7,13.7,144000,Birmingham-Hoover,AL,Metro,13820
4,"Bismarck, ND Metro Area",310M500US13900,127503,29171,78158,20174,22.9,61.3,15.8,249000,120688,27966,75829,16893,23.2,62.8,14.0,171000,Bismarck,ND,Metro,13900

# Now we start thinking about the kinds of change we want to look at.

With the measures I think the two most sensical ways to look at things are: percent change in the raw numbers, and change in population share.

First let's create the percent change:

In [198]:
data['O65percchange'] = round((data['O65'] - data['O*O65'])*100/data['O*O65'], 2)
data['taxbasepercchange'] = round((data['taxbase'] - data['O*taxbase'])*100/data['O*taxbase'], 2)
data['childpercchange'] = round((data['child'] - data['O*child'])*100/data['O*child'], 2)
data['totalpercchange'] = round((data['total']-data['O*total'])*100/data['O*total'], 2)
data['homepercchange'] = round((data['homevalue']-data['O*homevalue'])*100/data['O*homevalue'], 2)

Now change in share and real change:

In [199]:
data['O65sharechange'] = data['PO65'] - data['O*PO65']
data['taxbasesharechange'] = data['Ptaxbase'] - data['O*Ptaxbase']
data['childsharechange'] = data['Pchild'] - data['O*Pchild']
data['O65realchange'] = data['O65'] - data['O*O65']
data['taxbaserealchange'] = data['taxbase'] - data['O*taxbase']
data['childrealchange'] = data['child'] - data['O*child']
data['totalrealchange']= data['total'] - data['O*total']
data['homerealchange'] = data['homevalue'] - data['O*homevalue']

In [200]:
data.head()

,CBSA,GEOID,total,child,taxbase,O65,Pchild,Ptaxbase,PO65,homevalue,O*total,O*child,O*taxbase,O*O65,O*Pchild,O*Ptaxbase,O*PO65,O*homevalue,Name,State,Area,CBSAFIPS,O65percchange,taxbasepercchange,childpercchange,totalpercchange,O65sharechange,taxbasesharechange,childsharechange,O65realchange,taxbaserealchange,childrealchange,totalrealchange,homepercchange,homerealchange
0,"Big Stone Gap, VA Micro Area",310M500US13720,42456,8403,26596,7457,19.8,62.6,17.6,86200,60499,12375,38800,9324,20.5,64.1,15.4,82800,Big Stone Gap,VA,Micro,13720,-20.02,-31.45,-32.10,-29.82,2.2,-1.5,-0.7,-1867,-12204,-3972,-18043,4.11,3400
1,"Billings, MT Metro Area",310M500US13740,179071,41435,106634,31002,23.1,59.5,17.3,227900,162892,37974,100276,24642,23.3,61.6,15.1,187100,Billings,MT,Metro,13740,25.81,6.34,9.11,9.93,2.2,-2.1,-0.2,6360,6358,3461,16179,21.81,40800
2,"Binghamton, NY Metro Area",310M500US13780,241874,47899,148264,45711,19.8,61.3,18.9,117600,249261,50798,156323,42140,20.4,62.7,16.9,108800,Binghamton,NY,Metro,13780,8.47,-5.16,-5.71,-2.96,2.0,-1.4,-0.6,3571,-8059,-2899,-7387,8.09,8800
3,"Birmingham-Hoover, AL Metro Area",310M500US13820,1085330,250498,666052,168780,23.1,61.4,15.6,165200,1135534,267614,712019,155901,23.6,62.7,13.7,144000,Birmingham-Hoover,AL,Metro,13820,8.26,-6.46,-6.40,-4.42,1.9,-1.3,-0.5,12879,-45967,-17116,-50204,14.72,21200
4,"Bismarck, ND Metro Area",310M500US13900,127503,29171,78158,20174,22.9,61.3,15.8,249000,120688,27966,75829,16893,23.2,62.8,14.0,171000,Bismarck,ND,Metro,13900,19.42,3.07,4.31,5.65,1.8,-1.5,-0.3,3281,2329,1205,6815,45.61,78000

In [201]:
#index into where the Nashville MSA is to check the rankings out
nash = data.loc[data['CBSA'] == 'Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area'].reset_index(drop = True)

In [202]:
print("The following numbers are Nashville's percent growth in a 5 year over 5 year period for total elderly population, then the share change between the 2014 and 2019 periods:")
print('______________________________________________________________________________')
print(nash['O65percchange'])
print(nash['O65sharechange'])
print("The following number are Nashville's percent growth in a 5 year over 5 year period for total tax base population, then the share change between the 2014 and 2019 periods:")
print('______________________________________________________________________________')
print(nash['taxbasepercchange'])
print(nash['taxbasesharechange'])
print("The following number are Nashville's percent growth in a 5 year over 5 year period for total child population, then the share change between the 2014 and 2019 periods:")
print('______________________________________________________________________________')
print(nash['childpercchange'])
print(nash['childsharechange'])

The following numbers are Nashville's percent growth in a 5 year over 5 year period for total elderly population, then the share change between the 2014 and 2019 periods:
______________________________________________________________________________
0    21.72
Name: O65percchange, dtype: float64
0    1.4
Name: O65sharechange, dtype: float64
The following number are Nashville's percent growth in a 5 year over 5 year period for total tax base population, then the share change between the 2014 and 2019 periods:
______________________________________________________________________________
0    6.97
Name: taxbasepercchange, dtype: float64
0   -0.7
Name: taxbasesharechange, dtype: float64
The following number are Nashville's percent growth in a 5 year over 5 year period for total child population, then the share change between the 2014 and 2019 periods:
______________________________________________________________________________
0    4.9
Name: childpercchange, dtype: float64
0   -0.7
Name: childsharechange, dtype: float64

In [203]:
data.corr()

,total,child,taxbase,O65,Pchild,Ptaxbase,PO65,homevalue,O*total,O*child,O*taxbase,O*O65,O*Pchild,O*Ptaxbase,O*PO65,O*homevalue,O65percchange,taxbasepercchange,childpercchange,totalpercchange,O65sharechange,taxbasesharechange,childsharechange,O65realchange,taxbaserealchange,childrealchange,totalrealchange,homepercchange,homerealchange
total,1.000000,0.996776,0.999834,0.991324,0.022526,0.139218,-0.135573,0.296189,0.998979,0.998252,0.998779,0.986379,0.042132,0.112103,-0.139169,0.293595,0.052483,0.066643,0.024503,0.051167,-0.043974,0.119169,-0.082522,0.968627,-0.007367,-0.513270,0.263047,0.116818,0.231464
child,0.996776,1.000000,0.996252,0.979604,0.048907,0.137094,-0.154529,0.289851,0.993515,0.998685,0.992831,0.972490,0.068566,0.107278,-0.157473,0.284507,0.055544,0.072750,0.030620,0.055734,-0.054973,0.130312,-0.081918,0.971172,0.042826,-0.466698,0.310093,0.126077,0.233671
taxbase,0.999834,0.996252,1.000000,0.990267,0.021029,0.144786,-0.139099,0.298241,0.998800,0.997814,0.998884,0.985251,0.040363,0.117735,-0.142825,0.295766,0.052573,0.066070,0.024230,0.050462,-0.044967,0.119159,-0.081420,0.968073,-0.006094,-0.514494,0.263273,0.115428,0.232720
O65,0.991324,0.979604,0.990267,1.000000,-0.012608,0.116152,-0.088448,0.292854,0.993884,0.985059,0.993200,0.998838,0.007815,0.093388,-0.092449,0.294092,0.046532,0.058610,0.015753,0.046355,-0.021740,0.100014,-0.087102,0.953056,-0.091539,-0.573517,0.184483,0.106695,0.219154
Pchild,0.022526,0.048907,0.021029,-0.012608,1.000000,-0.247675,-0.577160,-0.167953,0.019360,0.043370,0.017047,-0.013836,0.972490,-0.348479,-0.516919,-0.212468,-0.028241,0.136117,0.168543,0.078346,-0.504359,0.408130,0.148330,-0.004212,0.083694,0.071602,0.073040,0.135155,-0.013905
Ptaxbase,0.139218,0.137094,0.144786,0.116152,-0.247675,1.000000,-0.648146,0.194061,0.135791,0.133677,0.140940,0.111705,-0.248103,0.971491,-0.679837,0.205510,0.164646,0.097582,0.064448,0.059199,-0.149379,0.164225,-0.005996,0.137799,0.077135,-0.008126,0.106766,-0.001729,0.118100
PO65,-0.135573,-0.154529,-0.139099,-0.088448,-0.577160,-0.648146,1.000000,-0.031886,-0.130172,-0.147281,-0.132698,-0.083713,-0.555172,-0.544866,0.979174,-0.006506,-0.116364,-0.189389,-0.187018,-0.111581,0.523143,-0.459284,-0.111553,-0.113401,-0.131409,-0.049434,-0.148038,-0.105074,-0.088970
homevalue,0.296189,0.289851,0.298241,0.292854,-0.167953,0.194061,-0.031886,1.000000,0.291279,0.287403,0.293168,0.284577,-0.138348,0.235053,-0.096440,0.974923,0.346336,0.220914,0.176982,0.243834,0.257087,-0.161708,-0.130979,0.328978,0.098560,-0.099603,0.176307,0.368569,0.823115
O*total,0.998979,0.993515,0.998800,0.993884,0.019360,0.135791,-0.130172,0.291279,1.000000,0.997177,0.999862,0.990962,0.038730,0.109283,-0.133647,0.290857,0.043099,0.055482,0.013879,0.040037,-0.042131,0.116487,-0.081621,0.958339,-0.052166,-0.549391,0.219190,0.106675,0.222193
O*child,0.998252,0.998685,0.997814,0.985059,0.043370,0.133677,-0.147281,0.287403,0.997177,1.000000,0.996588,0.979977,0.063552,0.104308,-0.150422,0.284042,0.046059,0.060872,0.018018,0.043803,-0.050987,0.128294,-0.084309,0.963563,-0.003702,-0.511418,0.263769,0.116073,0.226751
O*taxbase,0.998779,0.992831,0.998884,0.993200,0.017047,0.140940,-0.132698,0.293168,0.999862,0.996588,1.000000,0.990271,0.036024,0.114850,-0.136436,0.293127,0.043709,0.055043,0.014058,0.039709,-0.042124,0.114985,-0.080028,0.957731,-0.053311,-0.550694,0.217809,0.104802,0.222657
O*O65,0.986379,0.972490,0.985251,0.998838,-0.013836,0.111705,-0.083713,0.284577,0.990962,0.979977,0.990271,1.000000,0.005717,0.088800,-0.086425,0.287699,0.033878,0.046862,0.005084,0.034104,-0.025093,0.100395,-0.083444,0.937359,-0.135589,-0.605094,0.140103,0.097074,0.208064
O*Pchild,0.042132,0.068566,0.040363,0.007815,0.972490,-0.248103,-0.555172,-0.138348,0.038730,0.063552,0.036024,0.005717,1.000000,-0.370667,-0.520006,-0.181962,0.035171,0.160839,0.096428,0.089137,-0.389516,0.498650,-0.086119,0.020575,0.090691,0.052970,0.082805,0.115493,0.006268
O*Ptaxbase,0.112103,0.107278,0.117735,0.093388,-0.348479,0.971491,-0.544866,0.235053,0.109283,0.104308,0.114850,0.088800,-0.370667,1.000000,-0.600468,0.259328,0.207275,0.061883,0.090864,0.059170,-0.004006,-0.074314,0.083205,0.117152,0.057591,-0.001257,0.087263,-0.030998,0.116489
O*PO65,-0.139169,-0.157473,-0.142825,-0.092449,-0.516919,-0.679837,0.979174,-0.096440,-0.133647,-0.150422,-0.136436,-0.086425,-0.520006,-0.600468,1.000000,-0.081179,-0.220706,-0.195486,-0.166873,-0.131259,0.339221,-0.361242,-0.003196,-0.125293,-0.131026,-0.044591,-0.151503,-0.070996,-0.112153
O*homevalue,0.293595,0.284507,0.295766,0.294092,-0.212468,0.205510,-0.006506,0.974923,0.290857,0.284042,0.293127,0.287699,-0.181962,0.259328,-0.081179,1.000000,0.321685,0.159558,0.125026,0.189739,0.310622,-0.214552,-0.136211,0.318313,0.047081,-0.131213,0.129292,0.182207,0.676098
O65percchange,0.052483,0.055544,0.052573,0.046532,-0.028241,0.164646,-0.116364,0.346336,0.043099,0.046059,0.043709,0.033878,0.035171,0.207275,-0.220706,0.321685,1.000000,0.846605,0.734001,0.878040,0.387301,-0.169861,-0.270101,0.123522,0.186138,0.136473,0.213064,0.150334,0.325816
taxbasepercchange,0.066643,0.072750,0.066070,0.058610,0.136117,0.097582,-0.189389,0.220914,0.055482,0.060872,0.055043,0.046862,0.160839,0.061883,-0.195486,0.159558,0.846605,1.000000,0.900428,0.987418,-0.056927,0.152988,-0.100661,0.129256,0.231541,0.169344,0.254402,0.285901,0.324268
childpercchange,0.024503,0.030620,0.024230,0.015753,0.168543,0.064448,-0.187018,0.176982,0.013879,0.018018,0.014058,0.005084,0.096428,0.090864,-0.166873,0.125026,0.734001,0.900428,1.000000,0.930825,-0.166048,-0.106975,0.311471,0.081945,0.214673,0.202455,0.232782,0.282450,0.266930
totalpercchange,0.051167,0.055734,0.050462,0.046355,0.078346,0.059199,-0.111581,0.243834,0.040037,0.043803,0.039709,0.034104,0.089137,0.059170,-0.131259,0.189739,0.878040,0.987418,0.930825,1.000000,0.033986,0.002821,-0.043341,0.120823,0.226208,0.178600,0.250025,0.273541,0.323139
O65sharechange,-0.043974,-0.054973,-0.044967,-0.021740,-0.504359,-0.149379,0.523143,0.257087,-0.042131,-0.050987,-0.042124,-0.025093,-0.389516,-0.004006,0.339221,0.310622,0.387301,-0.056927,-0.166048,0.033986,1.000000,-0.611678,-0.503458,0.000507,-0.058866,-0.041868,-0.049955,-0.188836,0.058553
taxbasesharechange,0.119169,0.130312,0.119159,0.100014,0.408130,0.164225,-0.459284,-0.161708,0.116487,0.128294,0.114985,0.100395,0.498650,-0.074314,-0.361242,-0.214552,-0.169861,0.152988,-0.106975,0.002821,-0.611678,1.000000,-0.371418,0.092195,0.084835,-0.028949,0.086018,0.121703,0.012088
childsharechange,-0.082522,-0.081918,-0.081420,-0.087102,0.148330,-0.005996,-0.111553,-0.130979,-0.081621,-0.084309,-0.080028,-0.083444,-0.086119,0.083205,-0.003196,-0.136211,-0.270101,-0.100661,0.311471,-0.043341,-0.503458,-0.371418,1.000000,-0.105366,-0.027063,0.081357,-0.039154,0.087734,-0.086077
O65realchange,0.968627,0.971172,0.968073,0.953056,-0.004212,0.137799,-0.113401,0.328978,0.958339,0.963563,0.957731,0.937359,0.020575,0.117152,-0.125293,0.318313,0.123522,0.129256,0.081945,0.120823,0.000507,0.092195,-0.105366,1.000000,0.190229,-0.343985,0.453359,0.161368,0.276950
taxbaserealchange,-0.007367,0.042826,-0.006094,-0.091539,0.083694,0.077135,-0.131409,0.098560,-0.052166,-0.003702,-0.053311,-0.135589,0.090691,0.057591,-0.131026,0.047081,0.186138,0.231541,0.214673,0.226208,-0.058866,0.084835,-0.027063,0.190229,1.000000,0.781836,0.954873,0.221569,0.206179
childrealchange,-0.513270,-0.466698,-0.514494,-0.573517,0.071602,-0.008126,-0.049434,-0.099603,-0.549391,-0.511418,-0.550694,-0.605094,0.052970,-0.001257,-0.044591,-0.131213,0.136473,0.169344,0.202455,0.178600,-0.041868,-0.028949,0.081357,-0.343985,0.781836,1.000000,0.647521,0.110917,0.005049
totalrealchange,0.263047,0.310093,0.263273,0.184483,0.073040,0.106766,-0.148038,0.176307,0.219190,0.263769,0.217809,0.140103,0.082805,0.087263,-0.151503,0.129292,0.213064,0.254402,0.232782,0.250025,-0.049955,0.086018,-0.039154,0.453359,0.954873,0.647521,1.000000,0.244782,0.253809
homepercchange,0.116818,0.126077,0.115428,0.106695,0.135155,-0.001729,-0.105074,0.368569,0.106675,0.116073,0.104802,0.097074,0.115493,-0.030998,-0.070996,0.182207,0.150334,0.285901,0.282450,0.273541,-0.188836,0.121703,0.087734,0.161368,0.221569,0.110917,0.244782,1.000000,0.755345
homerealchange,0.231464,0.233671,0.232720,0.219154,-0.013905,0.118100,-0.088970,0.823115,0.222193,0.226751,0.222657,0.208064,0.006268,0.116489,-0.112153,0.676098,0.325816,0.324268,0.266930,0.323139,0.058553,0.012088,-0.086077,0.276950,0.206179,0.005049,0.253809,0.755345,1.000000

### Export

I'm going to export here and we can explore the data further in a new notebook - I want to separate prep for simplicity's sake.

In [204]:
data.to_csv('../output/csv/agegroupshomevalue_2014_2019_cbsa.csv', index = False)